name: Deploy to Production

on:
  push:
    branches:
      - main

env:
  MY_SECRET: ${{ secrets.API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Try '14' or '16' if '18' fails

    - name: Clear npm cache
      run: npm cache clean --force

    - name: Install dependencies
      run: npm install --verbose  # Enable verbose logging for more detail

    - name: Deploy
      run: npm run deploy  # Replace with actual deployment command
