name: Deploy to Production

on:
  push:
    branches:
      - user

env:
  MY_SECRET: ${{ secrets.API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # Try changing to 16 or 14 if 18 fails

    - name: Clear npm cache
      run: npm cache clean --force

    - name: Install dependencies
      run: npm install --verbose  # Added verbose logging

    - name: Deploy
      run: npm run deploy  # Replace with your actual deployment command
